---

- name: Run Composer Install
  composer:
    command="install"
    working_dir="{{ nex_app_build_code_base }}"
  become: yes
  become_user: "{{ nex_app_unix_user }}"
 
- name: Fix Perms
  shell: find var vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod u+w {} \; && chmod u+x bin/magento
  args:
    chdir: "{{ nex_app_build_code_base }}"
  become: yes
  become_user: "{{ nex_app_unix_user }}"

- name: Make Sure var/composer_home Exists
  file:
    path="{{ nex_app_build_code_base }}/var/composer_home"
    state="directory"
    mode=2751
  become: yes
  become_user: "{{ nex_app_unix_user }}"

- name: Check for var/composer_home Composer auth.json
  stat:
    path="{{ nex_app_build_code_base }}/var/composer_home/auth.json"
  register: var_composer_home_auth

- name: Install Composer var/composer_home/auth.json
  template:
    src="auth.json.j2"
    dest="{{ nex_app_build_code_base }}/var/composer_home/auth.json"
    mode="0644"
  become: yes
  become_user: "{{ nex_app_unix_user }}"
  when:
    - not var_composer_home_auth.stat.exists

- name: Generate app/etc/config.php
  shell: ./magento module:enable --all
  args:
    chdir: "{{ nex_app_build_code_base }}/bin"
    creates: "{{ nex_app_build_code_base }}/app/etc/config.php"
  become: yes
  become_user: "{{ nex_app_unix_user }}"

- name: Generate app/etc/env.php (with redis)
  template:
    src="env.redis.php.j2"
    dest="{{ nex_app_build_code_base }}/app/etc/env.php"
  become: yes
  become_user: "{{ nex_app_unix_user }}"
  when:
    - lb_redis_backnet_addrs is defined

- name: Generate app/etc/env.php (without redis)
  template:
    src="env.php.j2"
    dest="{{ nex_app_build_code_base }}/app/etc/env.php"
  become: yes
  become_user: "{{ nex_app_unix_user }}"
  when:
    - lb_redis_backnet_addrs is not defined

- name: Run deploy:mode:set production|developer
  command: bin/magento deploy:mode:set {{ magento_deploy_mode }}
    chdir="{{ nex_app_build_code_base }}"
  when:
    - inventory_hostname == groups['fs'][0]
    - magento_set_mode == true
  become: yes
  become_user: "{{ nex_app_unix_user }}"
